package com.reviewsbot;

public enum UserState {
    NONE,
    WAIT_SECRET,
    WAIT_PHONE_FOR_FIND,
    WAIT_TG_FOR_FIND,
    WAIT_NAME_FOR_FIND,
    WAIT_PHONE_FOR_REVIEW,
    WAIT_TG_FOR_REVIEW,
    WAIT_MAN_PHOTO,
    WAIT_MAN_NAME,
    WAIT_MAN_DESC,
    WAIT_REVIEW_TEXT,
    WAIT_EDIT_REVIEW_TEXT,
    WAIT_ADMIN_ADD_PHOTO,
    WAIT_ADMIN_ADD_NAME,
    WAIT_ADMIN_ADD_DESC,
    WAIT_ADMIN_ADD_CONTACT,
    WAIT_ADMIN_GRANT_PREMIUM_USER,
    WAIT_ADMIN_GRANT_PREMIUM_DAYS,
    WAIT_ADMIN_SET_PRICES,
    WAIT_ADMIN_ADD_ADMIN
}
